### PR TITLE
example of pagination

### PR DESCRIPTION
**Pull request by rvanheest**
This is an example of how to implement pagination in GraphQL. This is the result of a demo for @PaulBoon.

### Content of this PR
* a `relay` package with an extension on the basic pagination (added a `totalCount` field)
* change a `Seq[Person]` output to a `ExtendedConnection[Person]`
* added parameters for pagination: `first`, `last`, `before` and `after`

### Example
Below an example of how to use pagination. Assume 3 persons are known.
The first query asks for the first 2 persons and whether there are more (`hasNextPage`) and the resumption token (`endCursor`).
The second query uses this resumption token. The second response indicates there are no more results (`hasNextPage = false`), hence no third query needs to be submitted.

#### Example query (1)
```graphql
query GetPersonData {
  persons(first: 2) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        name
        givenname
        email
      }
    }
  }
}
```

#### Example response (1)
```json
{
  "data": {
    "persons": {
      "pageInfo": {
        "hasNextPage": true,
        "endCursor": "my-id-2"
      },
      "edges": [
        {
          "node": {
            "name": "name1",
            "givenName": "fullname1",
            "email": "my-email1@dans.knaw.nl"
          }
        },
        {
          "node": {
            "name": "name2",
            "givenName": "fullname2",
            "email": "my-email2@dans.knaw.nl"
          }
        }
      ]
    }
  }
}
```

#### Example query (2)
```graphql
query GetPersonData {
  persons(first: 2, after: "my-id-2") {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        name
        givenname
        email
      }
    }
  }
}
```

#### Example response (2)
```json
{
  "data": {
    "persons": {
      "pageInfo": {
        "hasNextPage": false,
        "endCursor": "my-id-3"
      },
      "edges": [
        {
          "node": {
            "name": "name3",
            "givenName": "fullname3",
            "email": "my-email3@dans.knaw.nl"
          }
        }
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by rvanheest** [comment]
For more examples, see https://github.com/DANS-KNAW/easy-deposit-properties

**Comment by PaulBoon** [comment]
Great @rvanheest, works for example with: 

```
query GetPersonData {
  persons(first: 2) {
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
    edges {
      node {
        id
        works {
          title
          authors (first: 10) {
            totalCount
            edges {
              node {
                id
              }
            }
          }
        }
      }
    }
  }
}
```

Note that Person data is minimal, only the 'id' is alway available (PRS ids), the other fields are sometimes empty.

**Comment by PaulBoon** [comment]
Note that paging is not optimal, because all person data is retrieved instead of only that needed for the 'page'. Also the person records are now cutoff at 1000 in VsoiDB.getAllPersons.

**Comment by wilkos-dans** [comment]
Very valuable. Thanks!

**Pull request merged**
